from Python2 to Python3
SAP/InfraBox pull request #444
Opened 2020-11-16 05:52 UTC by chengshifan

2020-11-16 05:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/InfraBox?pullRequest=444) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SAP/InfraBox?pullRequest=444) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: chengshifan<br/>:x: I517992<br/><hr/>**I517992** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/InfraBox?pullRequest=444) it.</sub>

2020-11-17 03:05 UTC, iberryful requested changes

2020-11-17 03:05 UTC, iberryful commented on ib.py
> +        print((line.rstrip()))
useless parenthesis

2020-11-17 03:05 UTC, iberryful commented on infrabox/test/api/job_api_test.py
> +            self.assertTrue(all(item in list(testresult_data["tests"][i].items())
useless wrapper

2020-11-17 03:05 UTC, iberryful commented on infrabox/test/e2e/test.py
> +            print((result.text))
useless parenthesis

2020-11-17 03:05 UTC, iberryful commented on infrabox/test/e2e/test.py
> +    print(("ROOT_URL: %s" % root_url))
useless parenthesis

2020-11-17 03:05 UTC, iberryful commented on infrabox/test/e2e/test.py
> +            print((r.text))
useless parenthesis

2020-11-17 03:05 UTC, iberryful commented on infrabox/test/e2e/tests/docker_compose_job/tests/tests.py
> +    print((r.json()))
useless parenthesis

2020-11-20 05:40 UTC, chengshifan commented on ib.py
> +        print((line.rstrip()))
done

2020-11-30 05:17 UTC, closed without merging